[package]
name = "core-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
sonic-rs = { workspace = true }
simdutf8 = { workspace = true }
twox-hash = { workspace = true }
compact_str = { workspace = true }
smallvec = { workspace = true }
base64-turbo = { workspace = true }
memchr = { workspace = true }
sha2 = { workspace = true }
sha1 = { workspace = true }
md-5 = { workspace = true }
hmac = "0.13"
pbkdf2 = { version = "0.13", default-features = false, features = ["hmac"] }

[dev-dependencies]
hex = { workspace = true }
